version: "3"

services:
  db:
    container_name: jenkins_db
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "15432:5432"
    # wait for db
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "test"]
        interval: 5s
        timeout: 5s
        retries: 5

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:alpine
    build: .
    environment:
      DEBUG: ''
      DATABASE_NAME: test
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      DATABASE_HOST: db
      REDIS_HOST: redis
    ports:
     - "9090:8080"
     - "50000:50000"
    depends_on:
     - db
